---
title: "index"
author: "Alex Vand"
date: "`r Sys.Date()`"
output: html_document
---

## Welcome
## 💩

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# get libraries
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  bbest/clockify,
  dplyr, DT, ggplot2,
  quiet = TRUE)

# CHANGE THESE VARIABLES!
api_txt <- "C:/Users/Alex Vand/Documents/EDS_211/clockify_api_key.txt"
project_name <- "jaws|bren"

# use API key to authenticate
CLOCKIFY_API_KEY <- readLines(api_txt)
set_api_key(CLOCKIFY_API_KEY)
```

## jaws|bren {.tabset}

### Overall

```{r}
# get data
d_times <- time_entries_all()
# table(d_times$project_name) # confirm project_name
d_times <- d_times %>%
  filter(
    project_name == !!project_name) %>%
  select(
    task_name, time_start, duration_hrs, 
    user_name, description) %>% 
  arrange(task_name, time_start)
```

```{r}
# plot ALL
plot_burndown(
  d_times,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-12-09"), # day after
  hrs = 40)

# table ALL
datatable(d_times)
```

### 1. Define Scope/Purpose/Plan

```{r}
task <- "Define Scope/Purpose/Plan"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-11-04"), # day after
  hrs = 5)

datatable(d_task)
```


### 2. Find Data and Import

```{r}
task <- "Find Data and Import"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-11-02"), # day before
  end = as.Date("2021-11-06"), # day after
  hrs = 5)

datatable(d_task)
```


### 3. Tidy (clean and combine) and Transform

```{r}
task <- "Tidy (clean and combine) and Transform"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-11-04"), # day before
  end = as.Date("2021-11-09"), # day after
  hrs = 5)

datatable(d_task)
```


### 4. Exploratory Visualization (Brainstorming)

```{r}
task <- "Exploratory Visualization (Brainstorming)"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-11-07"), # day before
  end = as.Date("2021-11-20"), # day after
  hrs = 5)

datatable(d_task)
```


### 5. Model/Refine

```{r}
task <- "Model/Refine"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-11-11"), # day before
  end = as.Date("2021-11-30"), # day after
  hrs = 10)

datatable(d_task)
```


### 6. Communicate

```{r}
task <- "Communicate"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-11-14"), # day before
  end = as.Date("2021-12-09"), # day after
  hrs = 10)

datatable(d_task)
```

